# Generated by Django 5.1.1 on 2024-10-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='last_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='contact_info',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='currency',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
