# Generated by Django 5.1.4 on 2024-12-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_remove_productprice_product_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='change',
            field=models.IntegerField(default=0),
        ),
    ]
