# Generated by Django 5.1.4 on 2024-12-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0007_likes_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sales', models.CharField(max_length=50)),
                ('shop', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=255)),
            ],
        ),
    ]
