# Generated by Django 5.1.4 on 2024-12-21 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
