# Generated by Django 5.1.4 on 2024-12-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_pricealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
