# Generated by Django 4.2.7 on 2024-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
    ]
